In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.1'

In [3]:
np.__doc__

'\nNumPy\n=====\n\nProvides\n  1. An array object of arbitrary homogeneous items\n  2. Fast mathematical operations over arrays\n  3. Linear Algebra, Fourier Transforms, Random Number Generation\n\nHow to use the documentation\n----------------------------\nDocumentation is available in two forms: docstrings provided\nwith the code, and a loose standing reference guide, available from\n`the NumPy homepage <https://numpy.org>`_.\n\nWe recommend exploring the docstrings using\n`IPython <https://ipython.org>`_, an advanced Python shell with\nTAB-completion and introspection capabilities.  See below for further\ninstructions.\n\nThe docstring examples assume that `numpy` has been imported as ``np``::\n\n  >>> import numpy as np\n\nCode snippets are indicated by three greater-than signs::\n\n  >>> x = 42\n  >>> x = x + 1\n\nUse the built-in ``help`` function to view a function\'s docstring::\n\n  >>> help(np.sort)\n  ... # doctest: +SKIP\n\nFor some objects, ``np.info(obj)`` may provide add

In [4]:
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
arr = np.array([1, 2, 3])
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr.dtype

dtype('int64')

In [7]:
arr = np.array(["1", 2, 3])
arr

array(['1', '2', '3'], dtype='<U21')

In [9]:
arr = np.array(["1", True, 3])
arr

array(['1', 'True', '3'], dtype='<U21')

In [11]:
arr = np.array([1, 2, 3], dtype=np.int8)
arr

array([1, 2, 3], dtype=int8)

In [13]:
arr = np.array([1, 2, 3])
arr, arr.dtype

(array([1, 2, 3]), dtype('int64'))

In [14]:
arr = np.array(range(1, 11))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.array([1, 2, 3], dtype=np.str_)
arr

In [16]:
l = ["red", "white", "green"]
np.array(l)

array(['red', 'white', 'green'], dtype='<U5')

In [17]:
l = ["1", "2", "3"]
np.array(l)

array(['1', '2', '3'], dtype='<U1')

In [19]:
l = [1, 2, 3]
np.array(l, dtype=np.str_)

array(['1', '2', '3'], dtype='<U1')

In [26]:
l = [[1, 2, 3], [4, 5, 6]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
l = [[1, 2, 3], [4, 5, 6]]
arr = np.array(l)
arr.shape

(2, 3)

In [29]:
l = [1, 2, 3, 4, 5, 6]
arr = np.array(l)
arr.shape

(6,)

In [30]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
np.linspace(0, 10, 6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [32]:
np.linspace(0, 11, 5)

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [33]:
np.linspace(0, 11, 5, dtype=np.int8)

array([ 0,  2,  5,  8, 11], dtype=int8)

In [37]:
arr = np.linspace(0, 11, 5)
arr.dtype

dtype('float64')

In [36]:
arr = np.linspace(0, 11, 5, dtype=np.int8)
arr.dtype

dtype('int8')

In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros(10, dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [40]:
np.zeros(3)

array([0., 0., 0.])

In [42]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.ones(3)

array([1., 1., 1.])

In [44]:
np.random.randint(0, 10)

4

In [45]:
import random

random.randint(0, 10)

0

In [46]:
np.random.randint(0, 10, 5)

array([5, 7, 1, 2, 8])

In [48]:
[random.randint(0, 10) for i in range(5)]

[5, 9, 0, 5, 9]

In [49]:
np.random.randint(0, 10, (2, 3))

array([[2, 1, 5],
       [8, 1, 2]])

In [53]:
[[random.randint(0, 10) for _ in range(3)] for _ in range(2)]

[[2, 0, 10], [5, 1, 4]]

In [55]:
arr = np.random.randint(0, 10, 10)
arr, arr[:3]

(array([6, 5, 5, 6, 1, 7, 2, 1, 7, 9]), array([6, 5, 5]))

In [56]:
arr = np.random.randint(0, 10, 10)
arr, arr[3]

(array([5, 4, 9, 3, 6, 2, 3, 6, 3, 1]), np.int64(3))

In [59]:
arr = np.random.randint(0, 10, (2,2))
arr, arr[0][1], arr[0, 1]

(array([[3, 7],
        [9, 5]]),
 np.int64(7),
 np.int64(7))

In [62]:
arr = np.random.randint(0, 10, 10)
print(arr)
arr.reshape(2, 5)

[4 3 6 2 0 0 3 8 4 3]


array([[4, 3, 6, 2, 0],
       [0, 3, 8, 4, 3]])

In [64]:
arr = np.random.randint(0, 10, 9)
print(arr)
arr.reshape(3, 3)

[9 9 8 0 4 2 4 2 8]


array([[9, 9, 8],
       [0, 4, 2],
       [4, 2, 8]])

In [71]:
arr = np.random.randint(0, 10, (2, 5))
print("intial arr:", arr)
print("arr[:,2]:", arr[:,0])
print("arr[0,:]:", arr[0,:])

intial arr: [[5 4 9 3 1]
 [8 1 2 0 0]]
arr[:,2]: [5 8]
arr[0,:]: [5 4 9 3 1]


In [74]:
arr = np.random.randint(0, 10, (2, 5))
print(arr)
print(len(arr))
print(arr.shape)


[[6 8 0 4 2]
 [8 4 4 8 9]]
2
(2, 5)


In [79]:
arr = np.random.randint(0, 3, 5)
print(arr)
sum(arr)


[2 2 1 2 2]


np.int64(9)

In [80]:
arr = np.random.randint(0, 3, (2, 2))
print(arr)
sum(arr)

[[1 2]
 [1 0]]


array([2, 2])

In [82]:
arr = np.random.randint(0, 3, (2, 2))
print(arr)
print(arr.sum())

[[2 0]
 [1 2]]
5


In [83]:
arr = np.random.randint(0, 3, (2, 2))
print(arr)
print("max=", arr.max())
print("min=", arr.min())
print("mean=", arr.mean())
print("std=", arr.std())


[[2 1]
 [0 0]]
max= 2
min= 0
mean= 0.75
std= 0.82915619758885


In [85]:
arr = np.linspace(0, 10, 11)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [87]:
arr = np.linspace(1, 10, 11)
np.log(arr)

array([0.        , 0.64185389, 1.02961942, 1.30833282, 1.5260563 ,
       1.70474809, 1.85629799, 1.98787435, 2.10413415, 2.20827441,
       2.30258509])

In [89]:
arr = np.linspace(-10, 1, 11)
print(arr)
print(np.absolute(arr))


[-10.   -8.9  -7.8  -6.7  -5.6  -4.5  -3.4  -2.3  -1.2  -0.1   1. ]
[10.   8.9  7.8  6.7  5.6  4.5  3.4  2.3  1.2  0.1  1. ]


In [90]:
arr = np.linspace(-10, 1, 11)
print(arr)
print(np.ceil(arr))

[-10.   -8.9  -7.8  -6.7  -5.6  -4.5  -3.4  -2.3  -1.2  -0.1   1. ]
[-10.  -8.  -7.  -6.  -5.  -4.  -3.  -2.  -1.  -0.   1.]


In [92]:
arr = np.linspace(-10, 1, 11)
print(arr)
print("max:", arr.max())
print("argmax:", arr.argmax())

[-10.   -8.9  -7.8  -6.7  -5.6  -4.5  -3.4  -2.3  -1.2  -0.1   1. ]
max: 1.0
argmax: 10


In [100]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print("arr1 + arr2:", arr1 + arr2)
print("arr1 - arr2:", arr1 - arr2)
print("arr1 * arr2:", arr1 * arr2)
print("arr1 / arr2:", arr1 / arr2)

arr1 + arr2: [4 6]
arr1 - arr2: [-2 -2]
arr1 * arr2: [3 8]
arr1 / arr2: [0.33333333 0.5       ]


In [103]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print(np.greater(arr1, arr2))
print(np.less_equal(arr1, arr2))

[False False]
[ True  True]


In [104]:
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print("arr1 * arr2:", arr1 * arr2)

arr1 * arr2: [3 8]


In [105]:
arr1 = np.array([[1, 2],
                 [1, 2]])
arr2 = np.array([[3, 4],
                 [3, 4]])

arr1 * arr2

array([[3, 8],
       [3, 8]])

In [106]:
arr2.T 

array([[3, 3],
       [4, 4]])

In [112]:
arr1 = np.array([[1, 2],
                 [1, 2]])
arr2 = np.array([[3, 4],
                 [3, 4]])

print("arr1 * arr2:\n", arr1 * arr2)
print("np.dot(arr1, arr2):\n", np.dot(arr1, arr2))


arr1 * arr2:
 [[3 8]
 [3 8]]
np.dot(arr1, arr2):
 [[ 9 12]
 [ 9 12]]


In [114]:
arr1 = np.array([[1, 2],
                 [1, 2]])
print(arr1.T)
print(arr1.transpose())

[[1 1]
 [2 2]]
[[1 1]
 [2 2]]


In [115]:
arr = np.array([[1, 2],
                 [1, 2]])
np.save("np_saved", arr)

In [ ]:
arr = np.load("np_saved.npy")
print(arr)

In [117]:
np.savetxt("np_saved.csv", arr)

In [118]:
new_arr = np.loadtxt("np_saved.csv")
print(new_arr)

[[1. 2.]
 [1. 2.]]
