In [1]:
import numpy as np

In [3]:
######### Exercise 1 ################
# Create a vector with 10 integer elements, all equal to 0.
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
print(np.array([0] * 10))

[0 0 0 0 0 0 0 0 0 0]


In [5]:
np.full(10, fill_value=0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.full(10, 0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
######### Exercise 2 ################
# Create a vector with 10 integer elements, all equal to 1.

In [11]:
arr= np.ones(10, dtype=np.int_)
arr, arr.dtype

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), dtype('int64'))

In [8]:
np.full(10, 1)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [3]:
######### Exercise 3 ################
# Create a vector with integer elements from 0 to 9.

In [12]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
######### Exercise 4 ################
# Create a vector with integer elements from 10 to 29.

In [13]:
np.arange(10, 30)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [5]:
######### Exercise 5 ################
# Create a vector with integer elements from 0 to 9 in reverse order.

In [14]:
np.arange(9, -1, -1)

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [16]:
np.arange(10)[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [6]:
######### Exercise 6 ################
# Create a vector with 10 random elements between 0 and 1.

In [18]:
np.random.randint(0, 2, 10)

array([0, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [19]:
np.random.rand(10)

array([0.31753643, 0.11151218, 0.356087  , 0.23133772, 0.68218504,
       0.35598966, 0.16184006, 0.1526192 , 0.21137858, 0.09514431])

In [21]:
np.random.randint(0, 10, 10) / 10

array([0.9, 0.8, 0.8, 0.8, 0.6, 0.7, 0. , 0.1, 0.1, 0.4])

In [27]:
np.random.randint(low=0, high=1000, size=10) / 1000

array([0.559, 0.053, 0.737, 0.086, 0.858, 0.758, 0.094, 0.562, 0.16 ,
       0.892])

In [7]:
######### Exercise 7 ################
# Create a 3x3 matrix with random integer elements between 0 and 9.

In [28]:
np.random.randint(0, 9, (3, 3))

array([[3, 4, 2],
       [6, 4, 5],
       [6, 1, 8]])

In [8]:
######### Exercise 8 ################
# Create a 5x5 identity matrix.

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
matrix = np.zeros((3, 3))
for i in range(len(matrix)):
    for j in range(len(matrix)):
        if i == j:
            matrix[i, j] = 1
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [35]:
######### Exercise 9 ################
# Add two matrices of equal dimensions (for example, 3x3).
m1 = np.random.randint(0, 2, (3, 3))
m2 = np.random.randint(0, 2, (3, 3))

print(m1)
print(m2)
print(m1+m2)

[[0 1 0]
 [0 0 0]
 [1 0 1]]
[[0 1 0]
 [1 1 1]
 [1 0 0]]
[[0 2 0]
 [1 1 1]
 [2 0 1]]


In [37]:
######### Exercise 10 ################
# Multiply two matrices of appropriate dimensions (for example, 2x3 and 3x2).

m1 = np.random.randint(0, 2, (2, 3))
m2 = np.random.randint(0, 2, (3, 2))
np.dot(m1, m2)

array([[0, 1],
       [0, 0]])

In [38]:
######### Exercise 11 ################
# Transpose a matrix (for example, 3x4).
m = np.random.randint(0, 2, (3, 4))
print(m)
print(m.transpose())
print(m.T)

[[1 0 0 1]
 [0 0 0 1]
 [1 0 0 1]]
[[1 0 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]]
[[1 0 1]
 [0 0 0]
 [0 0 0]
 [1 1 1]]


In [43]:
######### Exercise 12 ################
# Find the maximum value in a vector.
v = np.random.randint(0, 20, (1, 10))
v, v.max()

(array([[ 2, 17,  9,  6,  2, 11, 19,  1,  2,  8]]), np.int64(19))

In [45]:
######### Exercise 13 ################
# Find the index of the maximum value in a vector.
v = np.random.randint(0, 20, (1, 10))
v, v.max(), v.argmax()

(array([[ 7,  1,  9,  0, 12,  2,  3,  1,  8, 14]]), np.int64(14), np.int64(9))

In [46]:
######### Exercise 14 ################
# Find the arithmetic mean of the values in a matrix.
v = np.random.randint(0, 20, (1, 10))
v, v.mean()

(array([[ 0,  7, 14,  1,  7, 17,  4,  1,  2,  8]]), np.float64(6.1))

In [47]:
######### Exercise 15 ################
# Create a 4x4 matrix with random integer elements between 1 and 20.
np.random.randint(1, 20, (4, 4))

array([[10,  5, 16, 18],
       [12, 17,  6, 10],
       [18,  9, 13, 17],
       [ 9,  6,  6, 14]])

In [49]:
######### Exercise 16 ################
# Create a 6x6 diagonal matrix with diagonal elements equal to 5.
np.diag([5] * 3)

array([[5, 0, 0],
       [0, 5, 0],
       [0, 0, 5]])

In [51]:
np.diag([5, 6, ] )

array([[5, 0],
       [0, 6]])

In [53]:
######### Exercise 17 ################
# Reshape a vector of 12 elements into a 3x4 matrix.
v = np.array( [0] * 12)
print(v)
v.reshape(3, 4)

[0 0 0 0 0 0 0 0 0 0 0 0]


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [55]:
######### Exercise 18 ################
# Flatten a 3x4 matrix into a 1D array.
v = np.array( [0] * 12)
m = v.reshape(3, 4)
print(m)
m.flatten()

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
######### Exercise 19 ################
# Create a vector of length 50 with linearly spaced values between 0 and 100.
print((np.linspace(0, 100, 50, dtype=np.int_)))

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97 100]


In [65]:
np.round(np.linspace(0, 100, 50), 2)

array([  0.  ,   2.04,   4.08,   6.12,   8.16,  10.2 ,  12.24,  14.29,
        16.33,  18.37,  20.41,  22.45,  24.49,  26.53,  28.57,  30.61,
        32.65,  34.69,  36.73,  38.78,  40.82,  42.86,  44.9 ,  46.94,
        48.98,  51.02,  53.06,  55.1 ,  57.14,  59.18,  61.22,  63.27,
        65.31,  67.35,  69.39,  71.43,  73.47,  75.51,  77.55,  79.59,
        81.63,  83.67,  85.71,  87.76,  89.8 ,  91.84,  93.88,  95.92,
        97.96, 100.  ])

In [67]:
######### Exercise 20 ################
# Create a 5x5 matrix filled with a specific value (for example, 7).
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [21]:
######### Exercise 21 ################
# Create a vector of 15 random integers between 50 and 100, and sort it.

In [69]:
np.sort(np.random.randint(50, 100, 15))

array([54, 54, 55, 57, 72, 78, 81, 81, 81, 82, 85, 91, 93, 95, 96])

In [71]:
######### Exercise 22 ################
# Find the standard deviation of the values in a vector.
arr = np.random.randint(50, 100, 15)
print(arr)
arr.std()

[99 79 66 53 58 70 81 90 88 57 60 86 56 72 61]


np.float64(14.08766205664454)

In [72]:
######### Exercise 23 ################
# Replace all negative values in a vector with 0.
arr = np.array([0, 1, 2, 3, -4, -5])
arr[arr < 0]


array([-4, -5])

In [73]:
arr = np.array([0, 1, 2, 3, -4, -5])
arr[arr < 0] = 0
arr

array([0, 1, 2, 3, 0, 0])

In [80]:
######### Exercise 24 ################
# Create the leap years between two 1999 and 2101
arr = np.arange(2000, 2142, 4)
arr[(arr % 100 != 0) | (arr % 400 == 0)]

array([2000, 2004, 2008, 2012, 2016, 2020, 2024, 2028, 2032, 2036, 2040,
       2044, 2048, 2052, 2056, 2060, 2064, 2068, 2072, 2076, 2080, 2084,
       2088, 2092, 2096, 2104, 2108, 2112, 2116, 2120, 2124, 2128, 2132,
       2136, 2140])

In [81]:
######### Exercise 25 ################
# Create a random 4x4 matrix and compute the sum of all its elements.
matrix = np.random.randint(1, 20, (4, 5))
print(matrix)
matrix.sum()

[[18  7 15  4  8]
 [10  8 10 15 17]
 [15  2  4  6 12]
 [16  5  1 12  1]]


np.int64(186)